spring:
  application:
    name: store-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: store-auth
          uri: lb://store-auth
          predicates:
            - Path=/auth/**

        - id: store-account
          uri: lb://store-account
          predicates:
            - Path=/accounts/**
        
        - id: store-partner
          uri: lb://store-partner
          predicates:
            - Path=/partner/**
        
        - id: store-products
          uri: lb://store-products
          predicates:
            - Path=/products/**

        - id: insper
          uri: https://hsandmann.github.io/
          predicates:
            - Path=/

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
      POST /auth/register,
      POST /auth/login,
      ANY /auth/actuator,
      ANY /accounts/actuator,
      ANY /partner/actuator,
      ANY /products/actuator,
      ANY /gateway/actuator,
      ANY /auth/v3**,
      ANY /auth/swagger**,
      ANY /accounts/v3**,
      ANY /accounts/swagger**,
      ANY /products/v3**,
      ANY /products/swagger**,
      ANY /partner/v3**,
      ANY /partner/swagger**

